### ISSUE TITLE
problem in  StoredFeatures.rebuildIndexes 

### ISSUE THREAD

**Issue by zhhang920** [deegree/deegree3#1014]
Exception 
`java.lang.NullPointerException
Exception in thread "pool-7-thread-131" java.lang.RuntimeException
	at org.deegree.feature.persistence.cloudtaximemory.MemoryFeatureStore$1.next(MemoryFeatureStore.java:164)
	at org.deegree.feature.persistence.cloudtaximemory.MemoryFeatureStore$1.next(MemoryFeatureStore.java:146)
	at org.deegree.feature.stream.CombinedFeatureInputStream$1.hasNext(CombinedFeatureInputStream.java:106)
	at org.deegree.feature.stream.ThreadedFeatureInputStream$QueueFiller.run(ThreadedFeatureInputStream.java:150)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

problem in org.deegree.feature.persistence.cloudtaximemory.StoredFeatures.rebuildIndexes ,  can not clear ftToIndex at the beginning .

     public void rebuildRtrees() {
        ftToIndex.clear();
        ...
    }
public void rebuildRtrees() {
        Map<FeatureType, RTree<Feature>> tmp = new HashMap<FeatureType, RTree<Feature>>();
        ...
        ftToIndex = tmp;
    }

**Comment by tfr42** [comment]
Thanks for your feedback. Can you please post a complete deegree workspace for a reproducer.

And please have also a look on our https://github.com/deegree/deegree3/wiki/Bug-Report-writing-Guidelines and https://github.com/deegree/deegree3/wiki/Community-Support-Guidelines for further information.

**Comment by tfr42** [comment]
In the future please ask questions on the mailing list or GIS stackexchange. As mentioned in the [guidelines for contributing](https://github.com/deegree/deegree3/blob/master/CONTRIB.md#getting-in-contact), we prefer to use GitHub issues only for [bugs and enhancements](https://github.com/deegree/deegree3/wiki/Bug-or-Feature).
Please read further in our [community support guideline](https://github.com/deegree/deegree3/wiki/Community-Support-Guidelines).
