### ISSUE TITLE
Error "Table "DBF_INDEX" already exists" occurs in deegree-integration-tests

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#1297]
After upgrading to H2 with PR #1277 the following error occurs when executing "deegree-integration-tests":
```
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "DBF_INDEX" already exists; SQL statement:
create table dbf_index (record_number integer,file_index bigint, objectid double, elev double, shape_len double) [42101-210]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:521)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:227)
	at org.h2.message.DbException.get(DbException.java:203)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:88)
	at org.h2.command.CommandContainer.update(CommandContainer.java:174)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:209)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:169)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.deegree.feature.persistence.shape.DbfIndexImporter.importDbf(DbfIndexImporter.java:271)
	at org.deegree.feature.persistence.shape.DbfIndexImporter.createIndex(DbfIndexImporter.java:312)
	at org.deegree.feature.persistence.shape.DBFIndex.<init>(DBFIndex.java:81)
	at org.deegree.feature.persistence.shape.ShapeFeatureStore.init(ShapeFeatureStore.java:735)
	at org.deegree.workspace.standard.DefaultWorkspace.initAll(DefaultWorkspace.java:166)
	at org.deegree.commons.config.DeegreeWorkspace.initAll(DeegreeWorkspace.java:339)
	at org.deegree.services.controller.OGCFrontController.initWorkspace(OGCFrontController.java:1110)
	at org.deegree.services.controller.OGCFrontController.update(OGCFrontController.java:1195)
	at org.deegree.services.config.actions.Update.update(Update.java:46)
	at org.deegree.services.config.servlet.ConfigServlet.dispatch(ConfigServlet.java:136)
	at org.deegree.services.config.servlet.ConfigServlet.doGet(ConfigServlet.java:115)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
```

**Comment by tfr42** [comment]
Changes in h2 between 1.4 and 2.0 http://www.h2database.com/html/migration-to-v2.html
