### ISSUE TITLE
Test failures in current build of main branch

### ISSUE THREAD

**Issue by dstenger** [deegree/deegree3#1486]
See https://buildserver.deegree.org/job/deegree-3.5-release/lastCompletedBuild/org.deegree$deegree-wmts-tests/testReport/

Tests
* org.deegree.services.wmts.WmtsGetFeatureInfoSimilarityIT.testSimilarity[0]
* org.deegree.services.wmts.WmtsGetFeatureInfoSimilarityIT.testSimilarity[1]

fail with messages:
```
GetFeatureResponse does not match expected response cached_gfi, request: http://localhost:42157/deegree-wmts-tests/services?SERVICE=WMTS&REQUEST=GetFeatureInfo&VERSION=1.0.0&LAYER=remotewms_dominant_vegetation_cached&STYLE=default&TILEMATRIXSET=utah&TILEMATRIX=14285.714285714286&TILEROW=0&TILECOL=6&FORMAT=image%2Fpng&i=10&j=10&infoformat=text/html
. expected:<...evenStyle
td(row, '3[281815517.40000009').style.cssText = odd ? oddStyle : evenStyle
odd = !odd

row = tr(table)
td(row, 'length').style.cssText = odd ? oddStyle : evenStyle
td(row, '1283380.64562999993]').style.cssText = o...> but was:<...evenStyle
td(row, '3[.28181551740e+009').style.cssText = odd ? oddStyle : evenStyle
odd = !odd

row = tr(table)
td(row, 'length').style.cssText = odd ? oddStyle : evenStyle
td(row, '1.28338064563e+006]').style.cssText = o...>
```
```
org.junit.ComparisonFailure: 
GetFeatureResponse does not match expected response cached_gfi, request: http://localhost:42157/deegree-wmts-tests/services?SERVICE=WMTS&REQUEST=GetFeatureInfo&VERSION=1.0.0&LAYER=remotewms_dominant_vegetation_cached&STYLE=default&TILEMATRIXSET=utah&TILEMATRIX=14285.714285714286&TILEROW=0&TILECOL=6&FORMAT=image%2Fpng&i=10&j=10&infoformat=text/html
. expected:<...evenStyle
td(row, '3[281815517.40000009').style.cssText = odd ? oddStyle : evenStyle
odd = !odd

row = tr(table)
td(row, 'length').style.cssText = odd ? oddStyle : evenStyle
td(row, '1283380.64562999993]').style.cssText = o...> but was:<...evenStyle
td(row, '3[.28181551740e+009').style.cssText = odd ? oddStyle : evenStyle
odd = !odd

row = tr(table)
td(row, 'length').style.cssText = odd ? oddStyle : evenStyle
td(row, '1.28338064563e+006]').style.cssText = o...>
	at org.deegree.services.wmts.WmtsGetFeatureInfoSimilarityIT.testSimilarity(WmtsGetFeatureInfoSimilarityIT.java:104)
```
```
GetFeatureResponse does not match expected response remotewmsfi, request: http://localhost:42157/deegree-wmts-tests/services?SERVICE=WMTS&REQUEST=GetFeatureInfo&VERSION=1.0.0&LAYER=remotewms_dominant_vegetation&STYLE=default&TILEMATRIXSET=utah&TILEMATRIX=14285.714285714286&TILEROW=0&TILECOL=6&FORMAT=image%2Fpng&i=10&j=10&infoformat=text/html. expected:<...evenStyle
td(row, '3[281815517.40000009').style.cssText = odd ? oddStyle : evenStyle
odd = !odd

row = tr(table)
td(row, 'length').style.cssText = odd ? oddStyle : evenStyle
td(row, '1283380.64562999993]').style.cssText = o...> but was:<...evenStyle
td(row, '3[.28181551740e+009').style.cssText = odd ? oddStyle : evenStyle
odd = !odd

row = tr(table)
td(row, 'length').style.cssText = odd ? oddStyle : evenStyle
td(row, '1.28338064563e+006]').style.cssText = o...>
```
```
org.junit.ComparisonFailure: 
GetFeatureResponse does not match expected response remotewmsfi, request: http://localhost:42157/deegree-wmts-tests/services?SERVICE=WMTS&REQUEST=GetFeatureInfo&VERSION=1.0.0&LAYER=remotewms_dominant_vegetation&STYLE=default&TILEMATRIXSET=utah&TILEMATRIX=14285.714285714286&TILEROW=0&TILECOL=6&FORMAT=image%2Fpng&i=10&j=10&infoformat=text/html. expected:<...evenStyle
td(row, '3[281815517.40000009').style.cssText = odd ? oddStyle : evenStyle
odd = !odd

row = tr(table)
td(row, 'length').style.cssText = odd ? oddStyle : evenStyle
td(row, '1283380.64562999993]').style.cssText = o...> but was:<...evenStyle
td(row, '3[.28181551740e+009').style.cssText = odd ? oddStyle : evenStyle
odd = !odd

row = tr(table)
td(row, 'length').style.cssText = odd ? oddStyle : evenStyle
td(row, '1.28338064563e+006]').style.cssText = o...>
	at org.deegree.services.wmts.WmtsGetFeatureInfoSimilarityIT.testSimilarity(WmtsGetFeatureInfoSimilarityIT.java:104)
```

**Comment by lgoltz** [comment]
The failure occurs because the remote service returned length and area properties in scientific note [1].  
After rebuilding the container the GFI response contains length and area properties in decimal note as expected. Integration tests are successful: https://buildserver.deegree.org/view/Failing%20Jobs/job/pull-request/job/PR-1489/3

A possible explanation are h2 files created during reading the shape files (*mv.db). These was not removed during the last restart of the container. 

http://deegree3-demo.deegree.org/utah-workspace/services?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetFeatureInfo&BBOX=-113.59293044231728231,39.8263139704678153,-113.16734742896798593,40.728806591741197&SRS=EPSG:4326&WIDTH=398&HEIGHT=844&LAYERS=dominantvegetation&STYLES=&FORMAT=image/png&QUERY_LAYERS=dominantvegetation&INFO_FORMAT=text/html&X=304&Y=458

**Comment by stephanr** [comment]
Test failures were resolved by recreating the demo-instance.
See https://buildserver.deegree.org/job/pull-request/job/PR-1489/3/display/redirect

**Comment by tfr42** [comment]
Build jobs for all PR re-started. Failing integration test didn't reappear.
