### ISSUE TITLE
Button 'Setup tables' causes HTTP Status 500 – Internal Server Error

### ISSUE THREAD

**Issue by julianzz98** [deegree/deegree3#1662]
The error appears when you use the deegree webconsole and press the button 'Setup tables' on an activated 'Feature store' or 'Metadata store' configuration. 
![2024_03_08_0o1_Kleki](https://github.com/deegree/deegree3/assets/74777462/a0ab2ffd-244a-4909-96c6-22abf6901c61)

Once the button is pressed the HTTP Status 500 is presented:
![image](https://github.com/deegree/deegree3/assets/74777462/d68ab6fc-352e-4375-944b-11fea5ea7e43)

The deegree server logs are as following:
```
08-Mar-2024 13:17:30.989 SEVERE [http-nio-8080-exec-3] com.sun.faces.application.view.FaceletViewHandlingStrategy.handleRenderException Error Rendering View[/console/generic/sql.xhtml]
	javax.el.ELException: /console/generic/sql.xhtml @21,59 value="${xmlEditorBean.content}": Error reading [content] on type [org.deegree.console.generic.XmlEditorBean]
		at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:114)
		at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:194)
		at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:182)
		at javax.faces.component.UIOutput.getValue(UIOutput.java:174)
		at javax.faces.component.UIInput.getValue(UIInput.java:291)
		at org.primefaces.util.ComponentUtils.getValueToRender(ComponentUtils.java:122)
		at org.primefaces.util.ComponentUtils.getValueToRender(ComponentUtils.java:82)
		at org.primefaces.extensions.component.codemirror.CodeMirrorRenderer.encodeMarkup(CodeMirrorRenderer.java:112)
		at org.primefaces.extensions.component.codemirror.CodeMirrorRenderer.encodeEnd(CodeMirrorRenderer.java:94)
		at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:924)
		at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
		at javax.faces.render.Renderer.encodeChildren(Renderer.java:176)
		at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:894)
		at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304)
		at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:114)
		at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:894)
		at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304)
		at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:114)
		at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:894)
		at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304)
		at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:114)
		at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:894)
		at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)
		at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
		at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
		at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:456)
		at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:134)
		at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
		at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
		at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
		at javax.faces.webapp.FacesServlet.service(FacesServlet.java:647)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:829)
	Caused by: javax.el.ELException: Error reading [content] on type [org.deegree.console.generic.XmlEditorBean]
		at javax.el.BeanELResolver.getValue(BeanELResolver.java:100)
		at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:176)
		at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:203)
		at org.apache.el.parser.AstValue.getValue(AstValue.java:168)
		at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:189)
		at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:109)
		... 52 more
	Caused by: java.lang.NullPointerException
		at java.base/java.io.File.<init>(File.java:278)
		at org.deegree.console.generic.XmlEditorBean.getContent(XmlEditorBean.java:171)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at javax.el.BeanELResolver.getValue(BeanELResolver.java:95)
		... 57 more
```

The error was first detected by trying to reproduce the bug described in https://github.com/deegree/deegree3/issues/369 

**Affected versions: 3.5.5, 3.5.6**

**Comment by tfr42** [comment]
Bug was introduced with PR #1610, commit id: https://github.com/deegree/deegree3/pull/1610/commits/e91b851e4a5509d6ba7823f424a89d9d05b650a4
