### ISSUE TITLE
Import and following activation of official deegree-workspace-wps workspace causes UnsupportedClassVersionError in deegree 3.5.x

### ISSUE THREAD

**Issue by julianzz98** [deegree/deegree3#1754]
When importing the official deegree-workspace-wps and activating it with deegree version 3.5.x, the following error occurs:

```
2024-10-24 09:43:22,562 ERROR o.d.c.JsfUtils [http-nio-8080-exec-2] Workspace startup failed: org/deegree/wps/jts/CrossesProcesslet has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0(class java.lang.UnsupportedClassVersionError)
java.lang.UnsupportedClassVersionError: org/deegree/wps/jts/CrossesProcesslet has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1022) ~[?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555) ~[?:?]
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458) ~[?:?]
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[?:?]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527) ~[?:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:398) ~[?:?]
	at org.deegree.services.wps.provider.JavaProcessProvider.init(JavaProcessProvider.java:92) ~[deegree-services-wps-3.5.8.jar:3.5.8]
	at org.deegree.workspace.standard.DefaultWorkspace.initAll(DefaultWorkspace.java:164) ~[deegree-core-workspace-3.5.8.jar:3.5.8]
	at org.deegree.commons.config.DeegreeWorkspace.initAll(DeegreeWorkspace.java:335) ~[deegree-core-commons-3.5.8.jar:3.5.8]
	at org.deegree.services.controller.OGCFrontController.initWorkspace(OGCFrontController.java:1108) ~[deegree-services-commons-3.5.8.jar:3.5.8]
	at org.deegree.services.controller.OGCFrontController.reload(OGCFrontController.java:1175) ~[deegree-services-commons-3.5.8.jar:3.5.8]
	at org.deegree.console.workspace.WorkspaceBean.startWorkspace(WorkspaceBean.java:196) [deegree-webservices-3.5.8.jar:3.5.8]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.el.parser.AstValue.invoke(AstValue.java:252) [jasper-el.jar:9.0.89]
	at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:266) [jasper-el.jar:9.0.89]
	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105) [jsf-impl-2.2.20.jar:2.2.20]
	at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87) [javax.faces-api-2.2.jar:2.2]
	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102) [jsf-impl-2.2.20.jar:2.2.20]
	at javax.faces.component.UICommand.broadcast(UICommand.java:315) [javax.faces-api-2.2.jar:2.2]
	at com.sun.faces.facelets.component.UIRepeat.broadcast(UIRepeat.java:992) [jsf-impl-2.2.20.jar:2.2.20]
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790) [javax.faces-api-2.2.jar:2.2]
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282) [javax.faces-api-2.2.jar:2.2]
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81) [jsf-impl-2.2.20.jar:2.2.20]
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101) [jsf-impl-2.2.20.jar:2.2.20]
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198) [jsf-impl-2.2.20.jar:2.2.20]
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:646) [javax.faces-api-2.2.jar:2.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:199) [catalina.jar:9.0.89]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144) [catalina.jar:9.0.89]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) [tomcat-websocket.jar:9.0.89]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:168) [catalina.jar:9.0.89]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:144) [catalina.jar:9.0.89]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168) [catalina.jar:9.0.89]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) [catalina.jar:9.0.89]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) [catalina.jar:9.0.89]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) [catalina.jar:9.0.89]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) [catalina.jar:9.0.89]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660) [catalina.jar:9.0.89]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.89]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346) [catalina.jar:9.0.89]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:388) [tomcat-coyote.jar:9.0.89]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) [tomcat-coyote.jar:9.0.89]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928) [tomcat-coyote.jar:9.0.89]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) [tomcat-coyote.jar:9.0.89]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) [tomcat-coyote.jar:9.0.89]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190) [tomcat-util.jar:9.0.89]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:9.0.89]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) [tomcat-util.jar:9.0.89]
	at java.base/java.lang.Thread.run(Thread.java:829) [?:?]
```
In comparison, the error is not appearing when using deegree 3.6.0-pre2.

**Comment by dstenger** [comment]
Workspace was compiled with Java 17 but deegree instance uses Java 11 which leads to an incompatibility.
