### ISSUE TITLE
SQL highlighting does not work

### ISSUE THREAD

**Issue by bierett** [deegree/deegree3#369]
### Actual Behaviour

If I want to setup a metadata table (database) I can not turn on the SQL to highlighting.
### Expected Behaviour

If I click `Turn on highlighting` the SQL Statements will be highlighted.
### Additional information

See [deegree documentation](http://download.deegree.org/documentation/3.3.10/html/lightly.html#example-workspace-3-an-iso-catalogue-service-setup).

**Comment by julianzz98** [comment]
> While trying to replicate the reported bug in deegree version 3.5.3, a NPE is thrown out when pressing the button 'Setup tables' under a created metdata store:
> 
> ```
> 30-Nov-2023 13:51:16.977 SEVERE [http-nio-8080-exec-10] com.sun.faces.application.view.FaceletViewHandlingStrategy.handleRenderException Error Rendering View[/console/generic/sql.xhtml]
> 	javax.el.ELException: /console/generic/sql.xhtml @21,59 value="${xmlEditorBean.content}": Error reading [content] on type [org.deegree.console.generic.XmlEditorBean]
> 		at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:114)
> 		at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:194)
> 		at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:182)
> 		at javax.faces.component.UIOutput.getValue(UIOutput.java:174)
> 		at javax.faces.component.UIInput.getValue(UIInput.java:291)
> 		at org.primefaces.util.ComponentUtils.getValueToRender(ComponentUtils.java:122)
> 		at org.primefaces.util.ComponentUtils.getValueToRender(ComponentUtils.java:82)
> 		at org.primefaces.extensions.component.codemirror.CodeMirrorRenderer.encodeMarkup(CodeMirrorRenderer.java:112)
> 		at org.primefaces.extensions.component.codemirror.CodeMirrorRenderer.encodeEnd(CodeMirrorRenderer.java:94)
> 		at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:924)
> 		at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
> 		at javax.faces.render.Renderer.encodeChildren(Renderer.java:176)
> 		at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:894)
> 		at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304)
> 		at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:114)
> 		at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:894)
> 		at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304)
> 		at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:114)
> 		at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:894)
> 		at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304)
> 		at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:114)
> 		at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:894)
> 		at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)
> 		at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
> 		at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859)
> 		at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:456)
> 		at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:134)
> 		at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
> 		at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
> 		at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
> 		at javax.faces.webapp.FacesServlet.service(FacesServlet.java:647)
> 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
> 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
> 		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
> 		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
> 		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
> 		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
> 		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
> 		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
> 		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
> 		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
> 		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:670)
> 		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
> 		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
> 		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
> 		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
> 		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
> 		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
> 		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
> 		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
> 		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
> 		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 		at java.base/java.lang.Thread.run(Thread.java:829)
> 	Caused by: javax.el.ELException: Error reading [content] on type [org.deegree.console.generic.XmlEditorBean]
> 		at javax.el.BeanELResolver.getValue(BeanELResolver.java:100)
> 		at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:176)
> 		at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:203)
> 		at org.apache.el.parser.AstValue.getValue(AstValue.java:168)
> 		at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:189)
> 		at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:109)
> 		... 52 more
> 	Caused by: java.lang.NullPointerException
> 		at java.base/java.io.File.<init>(File.java:278)
> 		at org.deegree.console.generic.XmlEditorBean.getContent(XmlEditorBean.java:171)
> 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 		at javax.el.BeanELResolver.getValue(BeanELResolver.java:95)
> 		... 57 more
> ```

The reported NPE was fixed with [deegree-3.6.0-pre2](https://github.com/deegree/deegree3/releases/tag/deegree-3.6.0-pre2). Nevertheless, the primarily reported bug (syntax highlighting not working) still persists.
