### ISSUE TITLE
build issues because of deegree3-*.deegree.org not available

### ISSUE THREAD

**Issue by stephanr** [deegree/deegree3#513]
I had some problems running local builds with test and integraton-test enabled because some tests refferes to deegree3-demo.deegree.org and deegree3-testing.deegree.org, which are not available at the moment.
This maybe also apply to travis build (not yet tested)

I had seen at least one place where these services (utha-demo) are used directly and also in workspaces setup for remote-stores.

I thinks this may be relative to issue #488 and the migration of the demos.

@tfr42 Were the a different set of demos at deegree3-demo/deegree3-testing ?

A quick workaround test rewriting deegree3-demo and deegree3-testing to demo.deegree.org (via changed hosts entry and a apache with proxy) restored the failed test which directly reffered to deegree3-*.deegree.org.

If the demos where equal a possible solution would be to change the remaining dns C-NAMES and enhance the virtual-host configuration of the plaza.deegree.org.

**Comment by stephanr** [comment]
The Problem occoured on both lines 3.3 and 3.4

**Comment by tfr42** [comment]
> Were the a different set of demos at deegree3-demo/deegree3-testing?
Not that I am aware of. The target environment plaza.deegree.org shall host all the services of demo.deegree.org. The proposed fix to configure Apache httpd to rewrite deegree3-demo and deegree3-testing to demo.deegree.org sounds ok.

@wanhoff @NielsWalen Can you help out?

Long term goal is to get the integration tests self-contained and to avoid any access of external services. This would require major rework on the integration tests.

**Comment by stephanr** [comment]
The rewriting thing was a local test for me to check if the tests failed because of the remote demo or because of other issues.

For plaza.deegree.org i think it should suffice to add deeegree3-demo/deegree-testing to the vhost alias (This could be done by me), but the DNS C-NAME alias has to be changed by someone else.

**Comment by NielsWalen** [comment]
Both are added with pointer to plaza.deegree.org. Thanks for the hints.

**Comment by stephanr** [comment]
Ok, i had altered the Apache config on plaza.deegree.org so deegree3-demo/deegree3-testing/demo are now served by the same tomcat.

So we will see if that will fix the build problems.

**Comment by stephanr** [comment]
The failed test count reduced to one failed WMTS test which i suspect that the demo may have changed here, so i have to dig in here :-/
````
testCapabilitiesPyramidLayerNoFeatureInfoFormats(org.deegree.services.wmts.WmtsIT)  Time elapsed: 0.108 sec  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<12>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at org.deegree.services.wmts.WmtsIT.testCapabilitiesPyramidLayerNoFeatureInfoFormats(WmtsIT.java:99)
````


@tfr42 While lookin over the build output i noticed that there is a build pointing to cite.lat-lon.de which is not available anymore, do you know if this url may have changed ?
HTTP 404 http://cite.lat-lon.de/deegree-compliance-tests-3.1.2/services/wms?request=GetCapabilities&service=WMS&version=1.1.1

Referenced in these file:
3.3: [/deegree-workspaces/deegree-workspace-compliance-tests/src/main/workspace/datasources/remoteows/deegree-cite.xml](https://github.com/deegree/deegree3/blob/3.3-master/deegree-workspaces/deegree-workspace-compliance-tests/src/main/workspace/datasources/remoteows/deegree-cite.xml)
3.4: [/deegree-workspaces/deegree-workspace-compliance-tests/src/main/workspace/datasources/remoteows/deegree-cite.xml](https://github.com/deegree/deegree3/blob/master/deegree-workspaces/deegree-workspace-compliance-tests/src/main/workspace/datasources/remoteows/deegree-cite.xml)

**Comment by wanhoff** [comment]
Hi Stephan,

try http://cite.lat-lon.de/deegree-compliance-tests-3.3.1/ (but I'm not sure it's configured as 3.1.2 was)

It seems a good idea to remove the dependency to this service or host a copy on the deegree server.

Regards,
  Jeronimo

**Comment by tfr42** [comment]
The correct base URL for the CITE tests is:
​http://cite.deegree.org
Additional domain is reserved for the RI:
​http://ogcri.deegree.org
