### ISSUE TITLE
Upgrade jenkins CI on buildserver.deegree.org

### ISSUE THREAD

**Issue by tfr42** [deegree/deegree3#553]
Jenkins CI on buildserver.deegree.org needs urgently an update from 1.480.3 to the most recent version.
The target version shall be the LTS version 1.609.3.
Requires:
- backup of all jobs and jenkins configuration
- testing of all jobs after update

Plugins to update:

- [x] Maven Plugin
- [x] git Plugin

Tools:

- [x] JDK 8
- [x] Maven 3.5+

**Comment by stephanr** [comment]
As a intermediate soulution we changed the deegree-3.4-master build from maven-3.0.3 to maven-3.0.5.
This was required to resolve a artifact resulution problem regarding restricted jars.

**Comment by tfr42** [comment]
The update shall include maven 3.3.x too.

**Comment by tfr42** [comment]
Jenkins is unable to fetch git repo from GitHub due to:
```
ERROR: Problem fetching from origin/master / origin/master - could be unavailable. Continuing anyway
hudson.plugins.git.GitException: org.eclipse.jgit.api.errors.TransportException: git@github.com:deegree/deegree3.git: Algorithm negotiation fail
	at org.jenkinsci.plugins.gitclient.JGitAPIImpl.fetch(JGitAPIImpl.java:212)
...
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:237)
Caused by: org.eclipse.jgit.api.errors.TransportException: git@github.com:deegree/deegree3.git: Algorithm negotiation fail
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:137)
	at org.jenkinsci.plugins.gitclient.JGitAPIImpl.fetch(JGitAPIImpl.java:208)
	... 17 more
Caused by: org.eclipse.jgit.errors.TransportException: git@github.com:deegree/deegree3.git: Algorithm negotiation fail
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:142)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:121)
...
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:128)
	... 18 more
Caused by: com.jcraft.jsch.JSchException: Algorithm negotiation fail
	at com.jcraft.jsch.Session.receive_kexinit(Session.java:529)
	at com.jcraft.jsch.Session.connect(Session.java:291)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:116)
	... 25 more
```

http://buildserver.deegree.org/job/deegree-3.4-master/142/console

**Comment by tfr42** [comment]
Stop Tomcat:
```
systemctl stop tomcat_hudson
```

Backup HUDSON_HOME and Jenkins 1.480.3:
```
cp -R hudson-home hudson-home_bak
mv tomcat/webapps/ROOT ~/tmp/
mv tomcat/webapps/ROOT.war ~/tmp/
```
Get latestest Jenkins LTR and put it into Tomcat:
```
wget http://mirrors.jenkins.io/war-stable/latest/jenkins.war
mv jenkins.war tomcat/webapps/ROOT.war
```

Upgrade to OpenJDK8:
```
echo deb http://http.debian.net/debian jessie-backports main >> /etc/apt/sources.list
apt-get update
apt install -t jessie-backports  openjdk-8-jre-headless ca-certificates-java
apt-get install openjdk-8-jdk
```

Update start script:
changed `~/tomcat/bin/tomcat_hudson` and `/etc/systemd/system/tomcat_hudson.service`:
```
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
```
Reload system daemon:
```
systemctl daemon-reload
```

Start Tomcat
```
systemctl start tomcat_hudson
```

Jenkins Plugins updated:
- http://buildserver.deegree.org/pluginManager/

Job deegree-3.4 updated to use JDK 8:
http://buildserver.deegree.org/job/deegree-3.4-master/configure

**Comment by tfr42** [comment]
Upgraded Jenkins to 2.107.2 due to security warnings:
Jenkins 2.89.4 core and libraries:
Multiple security vulnerabilities in Jenkins 2.115 and earlier, and LTS 2.107.1 and earlier
Hudson SCP publisher plugin 1.8

**Comment by tfr42** [comment]
Upgraded Jenkins to 2.138.3 due to security warnings.

**Comment by tfr42** [comment]
continued in #956
