### ISSUE TITLE
Layer with filter using href not working

### ISSUE THREAD

**Issue by matteomatassoni** [deegree/deegree3#587]
I am not able to define a layer using a filter to check if a property coded in a xml `href` attribute is a certain literal.

```
<FeatureLayer>
    <FeatureType>ps:ProtectedSite</FeatureType>
    <Filter>
      <ogc:Filter>
        <ogc:PropertyIsEqualTo>
          <ogc:PropertyName>ps:siteDesignation/ps:DesignationType/ps:designationScheme/@xlink:href</ogc:PropertyName>
          <ogc:Literal>http://inspire.ec.europa.eu/codelist/DesignationSchemeValue/UNESCOManAndBiosphereProgramme</ogc:Literal>
        </ogc:PropertyIsEqualTo>
      </ogc:Filter>
    </Filter>
    <l:Name>PS.ProtectedSitesUNESCOManAndBiosphereProgramme</l:Name>
    <d:Title>Protected Sites - UNESCO Man and Biosphere Programme</d:Title>
    <s:CRS>EPSG:3035</s:CRS>
    <l:StyleRef>
      <l:StyleStoreId>PS_ProtectedSite_Default</l:StyleStoreId>
      <l:Style>
        <l:StyleName>PS.ProtectedSite.Default</l:StyleName>
        <l:LayerNameRef>PS.ProtectedSites</l:LayerNameRef>
        <l:StyleNameRef>PS.ProtectedSite.Default</l:StyleNameRef>
      </l:Style>
    </l:StyleRef>
  </FeatureLayer>
</FeatureLayers>
```

I found that the problem is in the `MappedXPath.java` class, see the attached trace log:

```
[16:58:20]  INFO: [AbstractWhereBuilder] Stack trace:
org.deegree.sqldialect.filter.UnmappableException: No mapping for PropertyName 'ps:siteDesignation/ps:DesignationType/ps:designationScheme/@xlink:href' available. Could not map step '@{http://www.w3.org/1999/xlink}href'.
    at org.deegree.feature.persistence.sql.xpath.MappedXPath.map(MappedXPath.java:207)
    at org.deegree.feature.persistence.sql.xpath.MappedXPath.map(MappedXPath.java:168)
    at org.deegree.feature.persistence.sql.xpath.MappedXPath.map(MappedXPath.java:168)
    at org.deegree.feature.persistence.sql.xpath.MappedXPath.map(MappedXPath.java:168)
    at org.deegree.feature.persistence.sql.xpath.MappedXPath.<init>(MappedXPath.java:135)
    at org.deegree.feature.persistence.sql.SQLPropertyNameMapper.getMapping(SQLPropertyNameMapper.java:69)
    at org.deegree.sqldialect.filter.AbstractWhereBuilder.toProtoSQL(AbstractWhereBuilder.java:856)
    at org.deegree.sqldialect.filter.AbstractWhereBuilder.toProtoSQL(AbstractWhereBuilder.java:715)
    at org.deegree.sqldialect.filter.AbstractWhereBuilder.toProtoSQL(AbstractWhereBuilder.java:361)
    at org.deegree.sqldialect.filter.AbstractWhereBuilder.toProtoSQL(AbstractWhereBuilder.java:303)
    at org.deegree.sqldialect.filter.AbstractWhereBuilder.toProtoSQL(AbstractWhereBuilder.java:620)
    at org.deegree.sqldialect.filter.AbstractWhereBuilder.toProtoSQL(AbstractWhereBuilder.java:307)
    at org.deegree.sqldialect.filter.AbstractWhereBuilder.build(AbstractWhereBuilder.java:178)
    at org.deegree.sqldialect.postgis.PostGISWhereBuilder.<init>(PostGISWhereBuilder.java:118)
    at org.deegree.sqldialect.postgis.PostGISDialect.getWhereBuilder(PostGISDialect.java:182)
    at org.deegree.feature.persistence.sql.SQLFeatureStore.getWhereBuilder(SQLFeatureStore.java:1523)
    at org.deegree.feature.persistence.sql.SQLFeatureStore.queryByOperatorFilter(SQLFeatureStore.java:1356)
    at org.deegree.feature.persistence.sql.SQLFeatureStore.query(SQLFeatureStore.java:964)
    at org.deegree.feature.persistence.sql.SQLFeatureStore$1.next(SQLFeatureStore.java:1014)
    at org.deegree.feature.persistence.sql.SQLFeatureStore$1.next(SQLFeatureStore.java:1)
    at org.deegree.feature.stream.CombinedFeatureInputStream$1.hasNext(CombinedFeatureInputStream.java:106)
    at org.deegree.feature.stream.CombinedFeatureInputStream.count(CombinedFeatureInputStream.java:151)
    at org.deegree.layer.persistence.feature.FeatureLayerData.render(FeatureLayerData.java:105)
    at org.deegree.services.wms.MapService.getMap(MapService.java:348)
    at org.deegree.services.wms.controller.WMSController.getMap(WMSController.java:639)
    at org.deegree.services.wms.controller.WMSController.handleRequest(WMSController.java:466)
    at org.deegree.services.wms.controller.WMSController.doKVP(WMSController.java:424)
    at org.deegree.services.controller.OGCFrontController.dispatchKVPRequest(OGCFrontController.java:807)
    at org.deegree.services.controller.OGCFrontController.doGet(OGCFrontController.java:373)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.deegree.client.core.filter.InputFileFilter.doFilter(InputFileFilter.java:75)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by matteomatassoni** [comment]
@MrSnyder I think the problem is related to `org.deegree.feature.persistence.sql.xpath.MappedXPath`

**Comment by matteomatassoni** [comment]
same bug as in #573
