### ISSUE TITLE
International characters in QName (3.4 RC1)

### ISSUE THREAD

**Issue by jarped** [deegree/deegree3#696]
In 3.4 RC1, deegree is unabe to load a featurestore which is set up to serve an application-schema that contains international characters (æøå in norwegian).

The same featurestore works in 3.3.18

Errormessage:

> Error near line 16, column 83: cvc-datatype-valid.1.2.1: 'app:RpOmrÃÂ¥de' is not a valid value for 'QName'.
> Error near line 16, column 83: cvc-attribute.3: The value 'app:RpOmrÃÂ¥de' of attribute 'name' on element 'FeatureTypeMapping' is not valid with respect to its type, 'QName'.

The feature is named app:RpOmråde

**Comment by tfr42** [comment]
@jarped  Can you please post the complete feature store configuration file.

**Comment by jarped** [comment]
Here's one that runs on the same schema, should give the same problems:
https://raw.githubusercontent.com/jarped/deegree.featurestores/reguleringsplaner/reguleringsplan_20160615.xml

**Comment by tfr42** [comment]
@jarped  SNAPSHOT Version for testing is available. Please get in contact with us if you can do some testing.

**Comment by jarped** [comment]
I've been testing some. I think the system default is being used. In my case this is windows-1252.

**java -version**
>java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

Running on Windows 10.

If I open an already existing featureStore (encoded id UTF-8), special characters seem to be interpreted as windows-1252.

I've also tried to copy config (https://raw.githubusercontent.com/jarped/deegree.featurestores/reguleringsplaner/reguleringsplan_20160615.xml) into the deegree-editor. When I then try to save it crashes:

> Caused by: java.io.CharConversionException: Invalid UTF-8 start byte 0xf8 (at char #1367, byte #-1)
        at com.ctc.wstx.io.UTF8Reader.reportInvalidInitial(UTF8Reader.java:303)
        at com.ctc.wstx.io.UTF8Reader.read(UTF8Reader.java:189)
        at com.ctc.wstx.io.ReaderSource.readInto(ReaderSource.java:87)
        at com.ctc.wstx.io.BranchingReaderSource.readInto(BranchingReaderSource.java:57)
        at com.ctc.wstx.sr.StreamScanner.loadMore(StreamScanner.java:991)

**Comment by dstenger** [comment]
Fix was merged for version 3.3 (#789).
PR for 3.4 is still open (#790).
