### ISSUE TITLE
Using of own valid application schema failed in deegree-webservices

### ISSUE THREAD

**Issue by mattenp** [deegree/deegree3#865]
Hi,

it's not possible to get an FeatureStore working by using an on application schema (memory store or blob-mode). The problem in deegree-webservice 3.3.20 and 3.4-RC3 is the book_entry_Type. It extends the gml:AbstractFeature by using the choice-element.
The xml-document is valid (XML-Spy).

**The Error in deegree is**: 
```
line: 224, column: 6, character offset: 12078): Property "{http://www.bsh.de/chartserver}b_description" is not allowed in features of type "{http://www.bsh.de/chartserver}book_entry" (or at least at this location).
<< is empty >>
	at org.deegree.gml.feature.GMLFeatureReader.parseFeatureStatic(GMLFeatureReader.java:359)
	at org.deegree.gml.feature.GMLFeatureReader.parseFeature(GMLFeatureReader.java:145)
	at org.deegree.gml.commons.AbstractGMLObjectReader.parseFeatureProperty(AbstractGMLObjectReader.java:284)
	at org.deegree.gml.commons.AbstractGMLObjectReader.parseProperty(AbstractGMLObjectReader.java:195)
	at org.deegree.gml.feature.GMLFeatureReader.parseFeatureStatic(GMLFeatureReader.java:363)
	at org.deegree.gml.feature.GMLFeatureReader.parseFeature(GMLFeatureReader.java:145)
	at org.deegree.gml.GMLStreamReader.readFeature(GMLStreamReader.java:286)
	at org.deegree.feature.persistence.memory.MemoryFeatureStoreProvider.create(MemoryFeatureStoreProvider.java:156)
	at org.deegree.feature.persistence.memory.MemoryFeatureStoreProvider.create(MemoryFeatureStoreProvider.java:82)
	at org.deegree.commons.config.AbstractResourceManager.create(AbstractResourceManager.java:115)
	at org.deegree.commons.config.AbstractResourceManager.processResourceConfig(AbstractResourceManager.java:262)
	at org.deegree.commons.config.AbstractResourceManager.startup(AbstractResourceManager.java:181)
	at org.deegree.feature.persistence.FeatureStoreManager.startup(FeatureStoreManager.java:112)
	at org.deegree.commons.config.DeegreeWorkspace.initAll(DeegreeWorkspace.java:403)
	at org.deegree.services.controller.OGCFrontController.initWorkspace(OGCFrontController.java:1133)
	at org.deegree.services.controller.OGCFrontController.init(OGCFrontController.java:1085)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1173)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:993)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4350)
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:4659)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:791)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:771)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:546)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1041)
	at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:964)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:502)
	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1277)
	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:321)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1053)
	at org.apache.catalina.core.StandardHost.start(StandardHost.java:785)
	at org.apache.catalina.core.ContainerBase.start(ContainerBase.java:1045)
	at org.apache.catalina.core.StandardEngine.start(StandardEngine.java:445)
	at org.apache.catalina.core.StandardService.start(StandardService.java:519)
	at org.apache.catalina.core.StandardServer.start(StandardServer.java:710)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:581)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)
```
**XML application schema product_small.xsd:**
```<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bsh="http://www.bsh.de/chartserver" xmlns:gml="http://www.opengis.net/gml/3.2" targetNamespace="http://www.bsh.de/chartserver" elementFormDefault="qualified" version="1.0">
	<annotation>
		<appinfo>
			<gmlProfileSchema xmlns="http://www.opengis.net/gml/3.2">http://www.opengis.net/gml/3.2</gmlProfileSchema>
		</appinfo>
	</annotation>
	<import namespace="http://www.opengis.net/gml/3.2" schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
	<element name="catalog" substitutionGroup="gml:AbstractFeatureCollection">
		<complexType>
			<complexContent>
				<extension base="gml:AbstractFeatureCollectionType">
					<sequence>
						<element ref="bsh:category"/>
					</sequence>
				</extension>
			</complexContent>
		</complexType>
	</element>
	<element name="category" substitutionGroup="gml:AbstractFeatureCollection">
		<complexType>
			<complexContent>
				<extension base="gml:AbstractFeatureCollectionType">
					<choice minOccurs="0" maxOccurs="unbounded">
						<element ref="bsh:book_entry" minOccurs="0" maxOccurs="unbounded"/>
					</choice>
				</extension>
			</complexContent>
		</complexType>
	</element>
	<element name="book_entry" type="bsh:book_entry_Type" substitutionGroup="gml:AbstractFeature"/>
	<complexType name="book_entry_Type">
		<complexContent>
			<extension base="gml:AbstractFeatureType">
				<choice minOccurs="0" maxOccurs="unbounded">
					<element ref="bsh:b_title"/>
					<!-- Buchtitel-->
					<element ref="bsh:b_subtitle" minOccurs="0"/>
					<!-- Untertitel -->
					<element ref="bsh:b_description" minOccurs="0"/>
					<!-- Beschreibung/Erläuterungen -->
					<element ref="bsh:b_bsh_number"/>
					<!-- interne BSH Nummer (Bestellnummer?) -->
					<element ref="bsh:b_sea_region" minOccurs="0"/>
					<!-- zugehöriges Seegebiet -->
					<element ref="bsh:b_edition"/>
					<!-- Erscheinungsjahr / Ausgabe -->
					<element ref="bsh:b_pages" minOccurs="0"/>
					<!-- Seitenzahl -->
					<element ref="bsh:b_format" minOccurs="0"/>
					<!-- Ausgabeformat -->
					<element ref="bsh:b_ISBN"/>
					<element ref="bsh:b_ISSN" minOccurs="0"/>
					<element ref="bsh:b_req_for_carr" minOccurs="0"/>
					<!-- Preis -->
					<element ref="bsh:b_price" minOccurs="0"/>
					<!-- Ausrüstungspflicht -->
					<element ref="bsh:b_preview" minOccurs="0"/>
					<!-- Vorschaubild -->
					<element ref="bsh:b_tag" minOccurs="0"/>
					<!-- Vorschaubild -->
					<!-- Kartendarstellung -->
					<element name="geom" type="bsh:PolygonType"/>
				</choice>
				<attribute name="entry_id" use="required"/>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="PolygonType">
		<sequence minOccurs="0">
			<element ref="gml:Polygon"/>
		</sequence>
	</complexType>
	<element name="b_title" type="string"/>
	<element name="b_subtitle" type="string"/>
	<element name="b_description" type="string"/>
	<element name="b_bsh_number" type="string"/>
	<element name="b_sea_region" type="string"/>
	<element name="b_edition" type="string"/>
	<element name="b_pages" type="string"/>
	<element name="b_format" type="string"/>
	<element name="b_ISBN" type="string"/>
	<element name="b_tag" type="string"/>
	<element name="b_ISSN" type="string"/>
	<element name="b_req_for_carr" type="string"/>
	<element name="b_price" type="string"/>
	<element name="b_preview" type="string"/>
</schema>
```

**XML document product_small.xml:**
```<?xml version="1.0" encoding="UTF-8"?>
<gml:FeatureCollection gml:id="id0xfffd4e70" xmlns="http://www.bsh.de/chartserver" xmlns:gts="http://www.isotc211.org/2005/gts" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:hfp="http://www.w3.org/2001/XMLSchema-hasFacetAndProperty" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:gss="http://www.isotc211.org/2005/gss" xmlns:gsr="http://www.isotc211.org/2005/gsr" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bsh.de/chartserver product_small.xsd">
	<gml:featureMember>
				<book_entry gml:id="id0x1077e0" entry_id="20001">
                                        <b_subtitle/>
					<b_title>Handbuch für Brücke und Kartenhaus</b_title>
					<b_description>Ratgeber und Informationsquelle für die sichere Schiffsführung in Ergänzung der Seekarten und Seebücher. Außerdem enthält es Hintergrundinformationen für Bereiche, die für die Schiffsführung und den Brücken- und Wachdienst von Bedeutung sind. In den technisch orientierten Kapiteln sind grundsätzliche Informationen über nautische Anlagen, Geräte und Instrumente sowie über Schifffahrtszeichen zusammengefasst.</b_description>
					<b_bsh_number>20001</b_bsh_number>
					<b_sea_region>21,16</b_sea_region>
					<b_edition>2016</b_edition>
					<b_pages>208</b_pages>
					<b_format>A4</b_format>
					<b_ISBN>978-3-86987-720-4</b_ISBN>
					<b_ISSN>1869-9936</b_ISSN>
					<b_req_for_carr>1</b_req_for_carr>
					<b_price>80,00</b_price>
					<b_preview>20001.png</b_preview>
					<b_tag>Handbuch</b_tag>
					<geom><gml:Polygon gml:id="id0x115060" srsName="urn:ogc:def:crs:epsg::4326">
						<gml:exterior>
							<gml:LinearRing>
								<gml:posList>70 -10 70 30 45 30 45 -10 70 -10</gml:posList>
							</gml:LinearRing>
						</gml:exterior>
					</gml:Polygon></geom>
				</book_entry>
			</gml:featureMember>
</gml:FeatureCollection>
```

Would it be possible to switch off the xml validation for the feature store for a workaround?

Best regards,
Matthias

**Comment by tfr42** [comment]
Please verify expected behavior against recent [release candidate version 3.4-RC5](http://repo.deegree.org/content/repositories/public/org/deegree/deegree-webservices/3.4-RC5/deegree-webservices-3.4-RC5.war) and report your results here.

**Comment by mattenp** [comment]
Hi, it's the same problem in release candidate version 3.4-RC5. 

Error in XML document (file 'produktkatalog_appSchema.xml', line: 19, column: 5, character offset: 1753): Property "{http://www.bsh.de/chartserver}b_title" is not allowed in features of type "{http://www.bsh.de/chartserver}book_entry" (or at least at this location).'. 

It seems that the deegree validator can't handle the xsd-element choice, propably it only knows the xsd-element sequence. If I switch b_title and subtitle to `<element ref="bsh:b_subtitle" minOccurs="0"/><element ref="bsh:b_title"/>` then it works, but this is not a choice, that's a sequence.

**Comment by mattenp** [comment]
Hi,

I am not sure, but perhaps choice is not allowed in the INSPIRE context concerning to gml:AbstractFeatureCollectionType. We have generated a new XML schema without using of choice-element and now it runs.

Best regards,
Matthias
